### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by edimuj** [edimuj/cordova-plugin-audioinput#1]
Implement iOS support using Audio Units.

**Comment by wilsonlmh** [comment]
Good job!! May I ask will iOS support soon?

**Comment by edimuj** [comment]
Thanks! I have a rough solution for iOS ready, and hope that I will be able to finish it in the coming weeks.

**Comment by joedaniels29** [comment]
Hm. Maybe not? haha I'm looking for a cordova plugin that will capture audio and work with Steroids.js (😭 don't use steroids.)

**Comment by edimuj** [comment]
The iOS implementation of the plugin is now ready. :)
