### ISSUE TITLE
[QUESTION] Is the audio recorded free of filters like noise cancellation?

### ISSUE THREAD

**Issue by asztern** [edimuj/cordova-plugin-audioinput#120]
Hi, we need to record an audio and make sure is filters free. That includes not having the noise cancellation filter active and others. Is this possible with this plugin?

Thank you in advance 
Ariel

**Comment by TobiasFPJS** [comment]
That is possible in the app, but might not be 100% enforced on IOS ( a lot depends on apple) (read the documentation)
