### ISSUE TITLE
Audioinput stops recording if an audio is played with cordova-media-plugin

### ISSUE THREAD

**Issue by arturomf** [edimuj/cordova-plugin-audioinput#122]
Hi all, I'm having a weird issue using audioinput.

If I start recording with audioinput.start() and after that, I play an audio using cordova-media-plugin, audioinput stops recording.

I'm testing in an Ionic5 app in iOS. In console I have this log:

Error Code responded -50 in file [..]/platforms/ios/appname/Plugins/cordova-plugin-audioinput/AudioReceiver.m on line 161

Any idea?
Best Regards

**Comment by edimuj** [comment]
Yes, the problem is that both plugins rely on the AVAudioSession of the app and the media plugin isn't keen on sharing it with other plugins. Sorry this isn't something that can be fixed from this plugin.
