### ISSUE TITLE
capacitor version?

### ISSUE THREAD

**Issue by Arpapiemonte** [edimuj/cordova-plugin-audioinput#126]
Hi,
I'm trying to use this plugin with a ionic-capacitor app
I can install the plugin with (https://capacitorjs.com/docs/plugins/cordova):
```
npm install cordova-plugin-name
npx cap sync
```

With an `angular` app I manage to use the cordova-plugin.
With a `vue` app I can't.

Is scheduled a development of a capacitor version?
Is this plugin mantained?

Thanks

**Comment by edimuj** [comment]
Capacitator support would be a very welcome addition. I haven't much time to maintain this plugin myself nowadays, but it is an open-source project, so any one who wants to contribute to it are welcome to file a PR.

**Comment by losciur** [comment]
Hi @edimuj , sorry if I didin't reply, but I haven't time and knowledge to help you in this work.
I hope someone could help.
Thanks

**Comment by edimuj** [comment]
No problem at all!

**Comment by jukefr** [comment]
fyi for future reference on people finding this issue, had no problems with a capacitor and react project. Just install package and `npx cap sync`. And setup for typescript like explained in the readme of the repo. I dont know about vue but should also be fine.
Make sure to put the permission check inside of a `useEffect` call to make sure the components are actually all loaded right and thats about it.
The "webaudio live output" does not seem to work right though on android (just crackles) but thats another issue that doesnt concern this and is already brought up in other already opened issues. I ended up just having to use an encoder to just check that the raw pcm data we capture was actually good and it was.

```js
[...]
  const startCapture = async () => {
    audioinput.start(audioCfg );
  };

  useEffect(() => {
    // Check if we already have permission to record
    audioinput.checkMicrophonePermission(function (hasPermission: boolean) {
      if (hasPermission) {
        console.log("We already have permission to record.");
      } else {
        // Ask the user for permission to access the microphone
        audioinput.getMicrophonePermission(function (
          hasPermission: boolean,
          message: string
        ) {
          if (hasPermission) {
            console.log("User granted us permission to record.");
          } else {
            console.warn("User denied permission to record.");
          }
        });
      }
    });
  }, []);
[...]
```

**Comment by edimuj** [comment]
Thank you @jukefr !
