### ISSUE TITLE
Add support for cordova browser platform and/or cordova-simulate

### ISSUE THREAD

**Issue by edimuj** [edimuj/cordova-plugin-audioinput#13]
For development purposes, so that the plugin can run in the browser when running in the browser platform:
`cordova platform add browser`

The browser proxy should either provide dummy audio data (i.e. white noise) or rely on getUserMedia if it is supported in the current browser.

**Comment by Tattomoosa** [comment]
I already made a basic implementation of this in my project with getUserMedia to test in browser. It was pretty trivial to do. Basically, if getUserMedia is supported it uses that instead, and I plug either audioinput or the Media Stream Source into a gain node and deal with signal from the gain node from there on out.

I'm not sure that it's possible to support all the configuration options though. Maybe through some creative use of AudioNodes?

**Comment by edimuj** [comment]
Sounds really good, Matt! I agree, it it certainly possible to achieve most configuration options using AudioNodes, like mono<->stereo for example using ChannelSplitterNode and ChannelMergerNode. 

Right now, 100% support for all parameters is not needed and can be something to implement later on, just a way of smoothly using the plugin when emulated in the [Cordova Browser platform](https://github.com/apache/cordova-browser) would be great. And why not [cordova-simulate](https://github.com/Microsoft/cordova-simulate) support as well?

**Comment by edimuj** [comment]
Fixed by PR #52
