### ISSUE TITLE
Get iOS recording with stereo and 8-bit working properly

### ISSUE THREAD

**Issue by edimuj** [edimuj/cordova-plugin-audioinput#21]
Right now only mono and recording with bit depth of 16 works as it should in the iOS part of the plugin. It would be good to get it to work with stereo and/or 8-bit recording.

**Comment by Tattomoosa** [comment]
I can't find where I read this, but apparently iOS devices have a dedicated DSP chip for their microphones that handles noise reduction etc. it may be that it runs in 16 bit and the only way to get to 8 bit is to downsample?

**Comment by edimuj** [comment]
Yes, I believe you're right and that the best way to achieve this is to use an Audio Converter: https://developer.apple.com/library/ios/documentation/MusicAudio/Reference/AudioConverterServicesReference/

The hardware microphones on most iOS devices are mono, but recording can be performed when using a stereo supporting external (e.g. bluetooth) microphone.

I don't know how important this actually is, but the plugin should behave as platform independent as possible and try to deliver the equal functionality on all the supported platforms, so this is still a "nice to have feature" with low prio.

**Comment by edimuj** [comment]
Since there hasn't been any activity on this project for quite some time, I'm closing it. Feel free to reopen if a need arises.
