### ISSUE TITLE
Help about choose speaker to play audio

### ISSUE THREAD

**Issue by zyf0330** [edimuj/cordova-plugin-audioinput#22]
When I use iPhone to play wav with audioContext.destination, sound comes from 	
stethoscope. And if it is Android, it is from loudspeaker.
So how to choose?

**Comment by edimuj** [comment]
This is on iOS? You could use the [av-audio-session-adapter](https://github.com/eworx/av-audio-session-adapter) plugin and set the CategoryOptions to DEFAULT_TO_SPEAKER. I always use this plugin when building sound apps for iOS.

In your case the plugin should be used like this:

```
var AVAudioSessionAdapter = gr.eworx.AVAudioSessionAdapter;
var audioSession = new AVAudioSessionAdapter();
audioSession.setCategoryWithOptions(
    AVAudioSessionAdapter.Categories.PLAY_AND_RECORD,
    AVAudioSessionAdapter.CategoryOptions.MIX_WITH_OTHERS,
    AVAudioSessionAdapter.CategoryOptions.DEFAULT_TO_SPEAKER,
    function() {
        // Do something on success.
    }, 
    function() {
        // Handle the error.
    }
);
audioSession.getCategory(
    function(category) {
        // Do something with category value.
    }
);
```

I hope this helps.

**Comment by zyf0330** [comment]
You make me find another plugin [audiotoggle](https://github.com/alongubkin/audiotoggle) to do same thing, I will test. Thanks!

**Comment by edimuj** [comment]
Thanks for telling me about the audiotoggle plugin. Never heard about it before, but it looks really nice and easy to use for this type of thing.
