### ISSUE TITLE
Microphone Permissions on iOS 10

### ISSUE THREAD

**Issue by asineath** [edimuj/cordova-plugin-audioinput#29]
Will you add a permission request message for the microphone to comply with the iOS 10 security upgrade? The app crashes when the plugin is initiated without a specified permission request alert.

**Comment by edimuj** [comment]
Sorry, haven't had any time to look into that specific issue, due to other projects. In my own apps, I rely on the microphone plugin to handle permissions on iOS: https://github.com/amitgur/cordova-plugin-microphone

**Comment by khelkun** [comment]
This did the job for me:
https://www.npmjs.com/package/cordova-plugin-ios-microphone-permissions

**Comment by edimuj** [comment]
Closing this issue, since there haven't been any activity for a while. Just give me a shout, if you want it to be reopened.
