### ISSUE TITLE
Very high latency 

### ISSUE THREAD

**Issue by silverhawk184** [edimuj/cordova-plugin-audioinput#34]
Hello,
I am getting high latency while running via the WebAudioAPI. I am testing on a Nexus 6P, Android 7.1.1 with a crosswalk 19 app. 

```
audioinput.start({
    streamToWebAudio: true,
    normalize: true, //got noisy but still delayed audio
    concatenateMaxChunks: 1, // attempted to lower latency, went from 5 seconds (10) to 2 seconds (1)
    audioSourceType: audioinput.AUDIOSOURCE_TYPE.UNPROCESSED //got no audio
});
audioinput.connect(audioinput.getAudioContext().destination);
```

Is there anything else I can tweak?

**Comment by edimuj** [comment]
I do not understand, you don't get any sound at all with the above settings, or you get sound with a 2s delay?

**Comment by edimuj** [comment]
Closing this issue, since there haven't been any activity for a while. Just give me a shout, if you want it to be reopened.
