### ISSUE TITLE
volume compare from mic ?

### ISSUE THREAD

**Issue by matrixreal** [edimuj/cordova-plugin-audioinput#39]
Hi,
is it possible to compare a volume from microphone ? something like low or high volume from microphone directly when we speak (ios cordova)
thanks

**Comment by edimuj** [comment]
Hi, not sure if I understand, but you could use the my speechcapture library together with this plugin, to get notified when the amplitude of the audio input reaches a certain level above the ambient sound level.

**Comment by edimuj** [comment]
Closing this issue, since there haven't been any activity for a while. Just give me a shout, if you want it to be reopened.
