### ISSUE TITLE
cannot compile for IOS swift version is wrong

### ISSUE THREAD

**Issue by alindzon** [edimuj/cordova-plugin-audioinput#45]
I cannot compile my app once this plugin is added.

Any chance someone can fix it for swift 3?

**Comment by edimuj** [comment]
@alindzon how do you build your app (phonegap build, local cordova build etc.)? What error(s) do you get?

**Comment by alindzon** [comment]
from visual studio remotely to the mac running xcode 8.  Worked fine until I added this plugin.
1>  Check dependencies
1>MDAVSCLI : warning : no rule to process file '/Users/dev/.taco_home/remote-builds/taco-remote/builds/2653/cordovaApp/platforms/ios/Zonechek/Plugins/cordova-plugin-audioinput/AudioReceiver.h' of type sourcecode.c.h for architecture armv7
1>  “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
1>MDAVSCLI : warning : no rule to process file '/Users/dev/.taco_home/remote-builds/taco-remote/builds/2653/cordovaApp/platforms/ios/Zonechek/Plugins/cordova-plugin-audioinput/AudioReceiver.h' of type sourcecode.c.h for architecture arm64
1>  “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
1>
1>  ** BUILD FAILED **

**Comment by alindzon** [comment]
also this information in the error list
Severity	Code	Description	Project	File	Line	Suppression State
Warning		no rule to process file '/Users/dev/.taco_home/remote-builds/taco-remote/builds/739/cordovaApp/platforms/ios/Zonechek/Plugins/cordova-plugin-audioinput/AudioReceiver.h' of type sourcecode.c.h for architecture armv7	z	C:\d\zc\z\MDAVSCLI	1	
Warning		no rule to process file '/Users/dev/.taco_home/remote-builds/taco-remote/builds/739/cordovaApp/platforms/ios/Zonechek/Plugins/cordova-plugin-audioinput/AudioReceiver.h' of type sourcecode.c.h for architecture arm64	z	C:\d\zc\z\MDAVSCLI	1	
Error		Error: Remote build error from the build server Build failed with error Error code 65 for command: xcodebuild with args: -xcconfig,/Users/dev/.taco_home/remote-builds/taco-remote/builds/739/cordovaApp/platforms/ios/cordova/build-release.xcconfig,-project,Zonechek.xcodeproj,-target,Zonechek,-configuration,Release,-destination,platform=iOS,build,CONFIGURATION_BUILD_DIR=/Users/dev/.taco_home/remote-builds/taco-remote/builds/739/cordovaApp/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/dev/.taco_home/remote-builds/taco-remote/builds/739/cordovaApp/platforms/ios/build/sharedpch - 1 	z		1

**Comment by edimuj** [comment]
Thanks. The ios part of this project is written in objective-c and not Swift. Which version of xcode 8 are you using, 8.3.x? Looks like this particular has been discussed here: https://stackoverflow.com/questions/43240035/xcode-8-3-swift-version-error-swift-version-in-objective-c-project

**Comment by alindzon** [comment]
Yes it is the latest xcode 8.3.3, i just updated it from an earlier release to see if that would fix it.

Since I am compiling remotely from VS 2015, I cannot figure out what I can do to fix this.  What file or files can I edit to allow the app to compile?  I even added https://www.npmjs.com/package/cordova-plugin-swift-support plugin to see if it would let me fix this in config.xml

**Comment by alindzon** [comment]
just removed cordova-plugin-swift-support, it broke android compile.

**Comment by alindzon** [comment]
I have also tried to compile locally on the mac after visual studio does its stuff, using the suggestion above, but that also fails but likely due to the way visual studio and xcode interact.  I suspect if I have to compile using xcode on its own I will have to reconstruct the project plugin by plugin on the mac, and move over the parts I wrote on their own (controllers and views mostly)

Does anyone have a solution?.

**Comment by alindzon** [comment]
i got it to compile using the method above, but when it runs it no longer functions with respect to the local file system.  It communicates with our server based APIs and executes a login, but when it tries to access the local file system, it is now undefined.  That code works fine in the version before I added this, and works no android, but no longer works on IOS.

**Comment by edimuj** [comment]
@alindzon have you tried this plugin to add Swift 3 support to your project?

**Comment by edimuj** [comment]
Since there hasn't been any activity on this project for some months now, I'm closing it. Feel free to reopen if a need arises.
