### ISSUE TITLE
Missing: cordova-plugin-file or cordova-plugin-audioinput!

### ISSUE THREAD

**Issue by d8bhatta** [edimuj/cordova-plugin-audioinput#47]
Hello,
I have installed cordova-plugin-audioinput plugin and  trying several ways of playing audo referencing demo folder. When i try using file-demo.html and copied its css and js files into www dir and run emulator, I get following error:

Missing: cordova-plugin-file or cordova-plugin-audioinput!

This error is coming from utils.js but not sure what is actual source.

Can you please suggest me how can  I resolve this issue. Its urgent!
Thank you in advance.

**Comment by edimuj** [comment]
Hi,

The file-demo needs to run in a cordova container, and your Cordova project needs to have the cordova-plugin-audioinput as well as the [cordova-plugin-file](https://github.com/apache/cordova-plugin-file) in order to work correctly.

**Comment by d8bhatta** [comment]
@edimuj  Thank you for your reply. I dont know whether file-demo is running in cordova-container or not, how can I make it running in the container?

The plugins I have are:

$ cordova plugin -l
cordova-plugin-audioinput 0.3.0 "Audio Input"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-media-capture 1.4.3 "Capture"
cordova-plugin-whitelist 1.3.2 "Whitelist"

 Please suggest!

Thanks

**Comment by edimuj** [comment]
Thanks, which emulator do you run the app in? Android or iOS? I have actually never tested the plugin on an emulator, so it would be good if you could test the plugin on a physical device.

**Comment by edimuj** [comment]
Since there haven't been any activity on this issue for some time, I'm closing it. If there is more information, feel free to open it again.
