### ISSUE TITLE
Start then stop then start again failed !

### ISSUE THREAD

**Issue by zamrokk** [edimuj/cordova-plugin-audioinput#48]
First time start is called, I receive data on my buffer
Then I call stop, the capturing is false

If I call start again, the capturing says true, but I receive nothing on my buffer. 
Neither the event listener for success or error is called in fact ...

I tried to remove it each time and adding it again but it changes nothing :(

**Comment by edimuj** [comment]
Could you please tell us something about your environment: Do you run in on iOS, Android, emulator, Cordova version etc?

**Comment by zamrokk** [comment]
ionic 2
cordova 7.0.1

using emulator on iOS

**Comment by edimuj** [comment]
I haven't actually tested this plugin on an emulator. Does it work as expected on a real device?

**Comment by zamrokk** [comment]
I do not have an iPhone

2017-08-22 16:44 GMT+02:00 Edin Mujkanovic <notifications@github.com>:

**Comment by edimuj** [comment]
Does it work on any real device? Android included.

**Comment by zamrokk** [comment]
Not yet tested.

I have passed to another solution using a native speech recognizer as the
speech to text api i was using with the audio was poor :/

2017-08-22 16:50 GMT+02:00 Edin Mujkanovic <notifications@github.com>:

**Comment by edimuj** [comment]
Ok, sounds like a good solution.

**Comment by zamrokk** [comment]
I don't know yet.... I see bugs too on the native recognizer. Maybe I will
finally be back and test with another speech to text API . Lol

Le 24 août 2017 11:50, "Edin Mujkanovic" <notifications@github.com> a
écrit :

**Comment by edimuj** [comment]
Well, good luck. I'm closing this issue for now, but feel free to reopen it or create a new one should the need arise.
