### ISSUE TITLE
Play remote audio file

### ISSUE THREAD

**Issue by d8bhatta** [edimuj/cordova-plugin-audioinput#49]
Hello,

I am trying to play remote audio file through this plugin. Here is my script https://pastebin.com/K08PbXU2

I can make sure that my audio file url is correct but still this plugin is not playing the audio.

Next, I have downloaded the audio file into cordova file system and tried to play it but its not playing. I have checked that the audio file exists in the system.

This is critical to my project and the project I am doing will help for blind people to know about surrounding so your answer is really very important.
Looking forward.

**Comment by edimuj** [comment]
Hi, the purpose of this plugin is to capture audio from the device microphone. So it isn't a multi-purpose audio plugin, and hasn't, therefore, any built-in support for playing back local or remote audio files. There are many other ways of playing back audio files, like for example the [cordova-plugin-media](https://github.com/apache/cordova-plugin-media), [cordova-plugin-nativeaudio](https://github.com/floatinghotpot/cordova-plugin-nativeaudio) or through HTML/javascript by using the Audio element and/or Web Audio API.
