### ISSUE TITLE
Android microphone permissions

### ISSUE THREAD

**Issue by finppp** [edimuj/cordova-plugin-audioinput#5]
Although <uses-permission android:name="android.permission.RECORD_AUDIO" /> is added in the AndroidManifest.xml,
The record function will not work until the permission is manually granted
(Settings -> Apps -> "appName" -> Permissions -> Microphone enable) 
I believe this is a new to Marshmallow.

**Comment by edimuj** [comment]
The new (microphone) permission handling on Android Marshmallow is likely be related to the problem. I haven’t yet had any time to perform any tests. It would be nice if it could be solved by this plugin though, so I will look into this in the beginning of next week.

**Comment by jamesst20** [comment]
Hi,

"Beginning in Android 6.0 (API level 23), users grant permissions to apps while the app is running, not when they install the app" Source : https://developer.android.com/training/permissions/requesting.html

"If your app needs a dangerous permission, you must check whether you have that permission every time you perform an operation that requires that permission. The user is always free to revoke the permission, so even if the app used the camera yesterday, it can't assume it still has that permission today."

```java
int permissionCheck = ContextCompat.checkSelfPermission(thisActivity, Manifest.permission.WRITE_CALENDAR); //Returns  PackageManager.PERMISSION_GRANTED or  PackageManager.PERMISSION_DENIED
```

If your app doesn't already have the permission it needs, the app must call one of the requestPermissions() methods to request the appropriate permissions. Your app passes the permissions it wants, and also an integer request code that you specify to identify this permission request. This method functions asynchronously: it returns right away, and after the user responds to the dialog box, the system calls the app's callback method with the results, passing the same request code that the app passed to requestPermissions().


```java
ActivityCompat.requestPermissions(thisActivity, new String[]{Manifest.permission.READ_CONTACTS}, MY_PERMISSIONS_REQUEST_READ_CONTACTS);

@Override
public void onRequestPermissionsResult(int requestCode, String permissions[], int[] grantResults) {
    switch (requestCode) {
        case MY_PERMISSIONS_REQUEST_READ_CONTACTS: {
            // If request is cancelled, the result arrays are empty.
            if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {

                // permission was granted, yay! Do the
                // contacts-related task you need to do.

            } else {

                // permission denied, boo! Disable the
                // functionality that depends on this permission.
            }
            return;
        }

        // other 'case' lines to check for other
        // permissions this app might request
    }
}
```
Waiting for the update :) 

Thank you !

**Comment by edimuj** [comment]
Thanks, James! I've added support for Android 6+ permissions for another project I was working on, so here it is.
