### ISSUE TITLE
Any way to detect blow in the microphone?

### ISSUE THREAD

**Issue by ma4xat** [edimuj/cordova-plugin-audioinput#50]
I want to differenciate if the users just talk or blow the microphone, for a happy birthday app :)

**Comment by edimuj** [comment]
@ma4xat I haven’t needed that type of functionality myself. The purpose of this plugin is to determine if there is sound that is comparable to speach for a minimum amount of time. If you find a way to add the functionality for blow detection, feel free to submit a PR.

**Comment by edimuj** [comment]
Since there hasn't been any activity on this project for some time now, I'm closing it. Feel free to reopen if a need arises.
