### ISSUE TITLE
Dependency with cordova-plugin-compat since cordova-android 6.3.0 ?

### ISSUE THREAD

**Issue by tchantchoj** [edimuj/cordova-plugin-audioinput#55]
Hello,

Now that cordova-plugin-compat is embedded in cordova-android 6.3.0, do you plan to remove the dependency with cordova-plugin-compat in this plugin?

Thanks.

**Comment by edimuj** [comment]
Hi, no it will not be removed, since that would break the builds for those that still run an older version of the Android platform. But I will specify, when I have some time, that the 1.2.0 version of the compat plugin is to be used, since that version automatically detects if it is needed or not.
