### ISSUE TITLE
Cordova Plugin Repository is not up to date

### ISSUE THREAD

**Issue by jdtzmn** [edimuj/cordova-plugin-audioinput#57]
I first installed this plugin from the cordova plugin registry:

`$ cordova plugin add cordova-plugin-audioinput`

But I got an error that it was missing the initialize method, and after checking the code, I can verify that it is missing.

Installing from the github page works though

**Comment by edimuj** [comment]
Thanks, @jdtzmn ! I will fix this ASAP.

**Comment by n1313** [comment]
It seems I am affected by this is well (can't check for microphone permissions).

**Comment by edimuj** [comment]
Ok, I've just published the latest version (1.0.0) to the npm repository.
