### ISSUE TITLE
Cannot read property '0' of undefined when encoding

### ISSUE THREAD

**Issue by floydus** [edimuj/cordova-plugin-audioinput#58]
I get this error, and seriously not getting why, seams the encoder fails to encode.  
It fails calling the encode method, I'm using the same parameters as the config, which is CD_AUDIO_44100Hz and STEREO, the array as some data in it (not zero length)
Any clues anyone ?  Thanks.
Here is a screenshot of the failing portion of code.
![screen shot 2018-02-07 at 2 41 18 pm](https://user-images.githubusercontent.com/19679654/35937700-0d89d7e0-0c15-11e8-87aa-371115b58a69.png)

**Comment by edimuj** [comment]
Do you get any details about how the encode execution fails?

On which type of device and OS does the error occur? Not all systems support all given parameters, have you tried differnt settings for mono/stereo and sample rate in the wavencoder?

**Comment by edimuj** [comment]
Since there haven't been any activity on this issue for a while now, I'm closing it, but feel free to open it again if you feel the need.

**Comment by floydus** [comment]
Thanks for coming back on this, I actually decided to look at other options, also, it's been too far behind and I just can't remember my issue at the time.  That is why I did not reply quickly. Thanks again Ed.

**Comment by edimuj** [comment]
No problems @floydus , thanks for the response.
