### ISSUE TITLE
Using with Ionic Platform

### ISSUE THREAD

**Issue by atlanlin** [edimuj/cordova-plugin-audioinput#6]
I am currently testing with Ionic platform but it stopped the application once `audioinput.start(captureCfg);` has been called. It just closes off the application so I can't see the error message as well.

**Comment by finppp** [comment]
Try either: changing the target apk to 22 instead of 23.
Or after installing the app go to settings, and manually tick the permissions

**Comment by edimuj** [comment]
Now the plugin supports both <23 and 23+ permission models.
