### ISSUE TITLE
Audio event not firing.

### ISSUE THREAD

**Issue by sarnold04** [edimuj/cordova-plugin-audioinput#60]
Hey everybody,

we wanted to include the plugin in our app, because we faced challenges with the webRTC possibilities on iOS.

After the plugin didn't work in our app, we built a demo app, but same problems there. I attached the files for this.

We are currently not getting an AudioInput event fired, but also no errors. We tested it on an iPad Mini 4 with iOS 11.3 and iPhone7 Plus with iOS 11.2.6.

Cordova: 8.0
Plugin-Version: 1.0.0

Do you have any ideas about this?

[config.xml.txt](https://github.com/edimuj/cordova-plugin-audioinput/files/1851686/config.xml.txt)
[index.js.txt](https://github.com/edimuj/cordova-plugin-audioinput/files/1851673/index.js.txt)
[index.html.txt](https://github.com/edimuj/cordova-plugin-audioinput/files/1851684/index.html.txt)

**Comment by sarnold04** [comment]
I've just tested the application on Android and it works just fine. All events are fired. From user point of view everything between iOS and Android is the same both are checking for microphone permission but after that Android is showing audio events and iOS does not.

**Comment by edimuj** [comment]
Thanks for the thourogh description. I will look into this tomorrow.
