### ISSUE TITLE
uses plugin.compat which is deprecated

### ISSUE THREAD

**Issue by alindzon** [edimuj/cordova-plugin-audioinput#61]
Can we get rid of that?

**Comment by edimuj** [comment]
From the README of https://github.com/apache/cordova-plugin-compat:
”This plugin is no longer being worked on as the functionality provided by this plugin is now included in cordova-android 6.3.0. **You should upgrade your application to use version 1.2.0 of this plugin. It will detect whether or not the plugin is required based on the version of cordova-android your app uses.**”

Cordova-plugin-audioinput uses 1.2.0 (see bolded text above).

**Comment by alindzon** [comment]
Yes, I ended up upgrading compat to 1.2 which seems to have resolved the build issues.
Thanks.



Warmest Regards,

Andrew Lindzon
647-388-3095

**Comment by edimuj** [comment]
Good to hear that it solved the problem @alindzon
