### ISSUE TITLE
Logo proposal for the application

### ISSUE THREAD

**Issue by richardbmx** [edimuj/cordova-plugin-audioinput#63]
Hello I would like to contribute in your application with a new logo icon I leave the proposal if you like I can send you all the files.... greetings ..

![logo152](https://user-images.githubusercontent.com/35604837/38046281-4acb47bc-328d-11e8-9d77-99405407a457.png)

**Comment by edimuj** [comment]
Hi, @richardbmx I like it and would gladly use it in the [app-audioinput-demo](https://github.com/edimuj/app-audioinput-demo). Really appreciate this! 🥇

**Comment by richardbmx** [comment]
Perfect that good that you liked I leave here the link with all the files of the icon and a logo version type.

All File [Google Drive](https://drive.google.com/open?id=1PEg0XMhMfqhgCjE0qBvmMa31UqPRxAFB)

**Comment by edimuj** [comment]
Thank you so much, @richardbmx 

I just added the logo as an icon to the app: https://github.com/edimuj/app-audioinput-demo/commit/b610e2bc422aa8d29e6774e05df392c9989cf43b

**Comment by edimuj** [comment]
Now also shown on in the README file: https://github.com/edimuj/app-audioinput-demo. Added you in the contributor section.

**Comment by richardbmx** [comment]
Perfect that good that you liked a pleasure to converse with you I am available for future applications has my support greeting ...
