### ISSUE TITLE
Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0

### ISSUE THREAD

**Issue by javaspaces** [edimuj/cordova-plugin-audioinput#67]
Hi,

I'm trying to use this plugin with my Android app, and when I try to add the plugin to my project, I get the following error message:

"Plugin doesn't support this project's cordova-android version. cordova-android: 7.0.0, failed version requirement: <6.3.0"

What can I do to resolve this issue?

**Comment by edimuj** [comment]
Actually this is not an error. This plugin depends on the [cordova-plugin-compat](https://github.com/apache/cordova-plugin-compat) v1.2.0, that only is used in older cordova projects. In newer projects, such as yours, the message above is shown indicating that the cordova-plugin-compat wasn't needed and therefore wasn't added. You can read more about this here: https://github.com/apache/cordova-plugin-compat
