### ISSUE TITLE
getMicrophonePermission not opening permission popup after denying it first time in iOS

### ISSUE THREAD

**Issue by kvharish** [edimuj/cordova-plugin-audioinput#70]
Used the below code given in example but "Ask the user for permission to access the microphone" part of the code does not open the permission popup the second time. Please note the first time I denied access.

// First check whether we already have permission to access the microphone.
window.audioinput.checkMicrophonePermission(function(hasPermission) {
	if (hasPermission) {
		console.log("We already have permission to record.");
		startCapture();
	} 
	else {	        
		// Ask the user for permission to access the microphone
		window.audioinput.getMicrophonePermission(function(hasPermission, message) {
			if (hasPermission) {
				console.log("User granted us permission to record.");
				startCapture();
			} else {
				console.warn("User denied permission to record.");
			}
		});
	}
});

Please forgive the alignment. Can someone help?

**Comment by robertfromont** [comment]
This is, unfortunately, a behaviour in iOS. If you deny access, iOS will never ask again, the user has to go into the app settings and explicitly enable microphone permission.
(On Android, there's a 'don't ask again' checkbox that has the same effect, but it's unchecked by default, so generally, they'll be repeated asked until they check the box or allow permission)

**Comment by kvharish** [comment]
Thanks for the clarification.
