### ISSUE TITLE
stereo recording

### ISSUE THREAD

**Issue by shi11** [edimuj/cordova-plugin-audioinput#76]
Hi, I'm trying out your plugin and first want to say great work! I'm specifically testing whether I can record in stereo. 

In your wav-demo.js file, I added CHANNELS.STEREO to this block 

`captureCfg = {
                audioSourceType: parseInt(audioSourceType),
                channels: window.audioinput.CHANNELS.STEREO
            };`

however I'm getting this error caught in stopCapture().

> "undefined is not an object (evaluating 'r[n][e]')"

any ideas? thanks in advance, Seth

**Comment by edimuj** [comment]
It sounds like the plugin isn't properly installed in your app for some reason. Does this error occur in mobile or in a browser? Do the window.audioinput object actually exists?

**Comment by edimuj** [comment]
Since there haven't been any activity on this issue for some months now, I'm closing it. Feel free to open it again if there is any change or new information.
