### ISSUE TITLE
bluetooth issue

### ISSUE THREAD

**Issue by libyenter** [edimuj/cordova-plugin-audioinput#77]
It's a very good plugin, really something I'm looking for.

I was playing your example code within an ionic APP on my iPhone, everything is fine, but I met a problem when I connect my Bluetooth earphone, the audio is still play to the speaker but not to the earphone (the wireless connection is ok, because when I play the Apple Music, it's in the earphone).

What I mean is I would like capture the signal from the mic in iPhone, and play it back through the Bluetooth earphone instead of the speaker in iPhone.

Do you know any work around for that?

Thank you very much!

**Comment by edimuj** [comment]
I would use another plugin for that, like for example: https://github.com/danielflippance/audiotoggle or https://github.com/saghul/cordova-plugin-audioroute

**Comment by edimuj** [comment]
Since there haven't been any activity on this issue for some months now, I'm closing it. Feel free to open it again if there is any change or new information.
