### ISSUE TITLE
speechcapture link/project disappeared

### ISSUE THREAD

**Issue by olivermuc** [edimuj/cordova-plugin-audioinput#89]
Edin,
Any chance you can share this library with us again? 
It's exactly what I am looking for - much appreciated!
Oliver

**Comment by edimuj** [comment]
The reason why that library disappeared is that it was licensed to a company for commercial use a couple of years ago.

**Comment by olivermuc** [comment]
Thanks Edin.
Any pointers though as to how to read/process your event data to determine low volume for a particular duration?

**Comment by edimuj** [comment]
That code by @cwilso (the god of audio processing) is a good starting point. It basically detects clipping (audio levels which are too high and leads to annoying clicks), but it should be possible to use the same method to detect audio above a certain (lower) level and then combine it with functionality that captures only that audio from the incoming audio data stream.

**Comment by olivermuc** [comment]
Right, thanks for confirming. I was first thinking that I might get away with simply creating avg data values across recorded (event) chunks and subtract a "certain" ambient volume level.
But wasn't sure that's exactly what I need to do, it feels too easy, lol.
