### ISSUE TITLE
How to convert tha audio data received from the event trigger?

### ISSUE THREAD

**Issue by artorralbaiii** [edimuj/cordova-plugin-audioinput#92]
Hi,

May I know how to convert the "evt.data" to base64 format? Currently, the format it is throwing is an Array of numbers.

function onAudioInput( evt ) {
    console.log( "Audio data received: " + evt.data.length + " samples" );
}

**Comment by zhaoxu666** [comment]
I have a same problem!!! how to save evt.data in this.file.externalDataDirectory

**Comment by edimuj** [comment]
Have you looked at the demo project? There is an example there on how to convert the raw audio data to WAV format and another example shows how to save it as a file using cordova-plugin-file:

WAV format: https://github.com/edimuj/app-audioinput-demo/blob/master/www/js/wav-demo.js
Save WAV to file: https://github.com/edimuj/app-audioinput-demo/blob/master/www/js/file-demo.js

**Comment by edimuj** [comment]
Since there haven't been any activity on this issue for a month now, I'm closing it. Feel free to get back to me if there is any update.
