### ISSUE TITLE
Variabile undefined

### ISSUE THREAD

**Issue by marsiliflavio** [edimuj/cordova-plugin-audioinput#93]
Hi,
have have current problem. In my develop repository i have paste the code from the demo example, the plugin is correctly install and present in package.json and config.xml. But, when start my app mobile at deviceready obtain audioinput undefined. Cordova is ready, obtain info from mobile, other plugin is correctly stared (camera, network...), but audioinput is null/undefined. Watching window variable, audioplugin is not present

**Comment by edimuj** [comment]
@marsiliflavio Do you run the project on a device, emulator or in a desktop browser?

**Comment by marsiliflavio** [comment]
On device. I have a contract in the cloud repository and the provider have an app for debug my projects

**Comment by edimuj** [comment]
Which provider do you use to build your app? If it is a generic pre-built test app, I would guess that it doesn't include this plugin, which would explain your issue. You need to build the app yourself if that is the case.

**Comment by marsiliflavio** [comment]
Monaca.io
debugger app installed in my mobile phone (ios and android). 
I have the possibility to include custom plugins directly from git url. your plugin is regularly included in config.xml and packages.json.
I use other custom plugins. For example https://github.com/cordova-plugin-camera-preview/cordova-plugin-camera-preview.
This works regularly in the same project

Thanks

**Comment by edimuj** [comment]
Ok, thanks. Sadly I aren't able to test this since Monaca with the custom debugger costs money.

Are you able to see the build logs from Monaca? It would be interesting to see what happens during build time.

Have you imported the plugin in the Monaca portal as stated in their docs? https://docs.monaca.io/en/products_guide/monaca_cli/dependencies/custom_cordova_plugin/

> "Please make sure to import the custom or external third-party Cordova plugins before building the custom built debugger."

**Comment by marsiliflavio** [comment]
"Please make sure to import the custom or external third-party Cordova plugins before building the custom built debugger". Yes, i do..,but I will proceed with new tests on a new project. Maybe something goes into conflict or something doesn't work.
hank you so much

**Comment by edimuj** [comment]
Ok, I understand, I know it is frustrating when these things doesn't work. I wish you good luck @marsiliflavio and we'll let this issue remain opened a while longer, so keep me updated of any progress or if the issue persists.

**Comment by marsiliflavio** [comment]
Hi,
all solved, a configuration problem, internal to the project. I apologize for the attempted alarm on possible bugs of the plugin and I thank you for the work and availability.

best regards

**Comment by edimuj** [comment]
No problem at all and thanks for the update @marsiliflavio.
