### ISSUE TITLE
Dose it support android 4.4?

### ISSUE THREAD

**Issue by wangzhengbo** [edimuj/cordova-plugin-audioinput#97]
Dose it support android 4.4?

When test it on android 4.4 emulator, app crashed after invoke start() methods.

**Comment by edimuj** [comment]
It "should" work, but since I haven't tested it myself, I cannot say for sure. 

Anybody else here have experience of running it on Android 4.4?

**Comment by wangzhengbo** [comment]
I test it on Android 4.4. It works well.

**Comment by edimuj** [comment]
Thanks for the update @wangzhengbo 

It seems like the plugin doesn't work in the Android emulator then.
